name: 'Checkout'
description: 'Checkout a repository'
inputs:
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: true
    default: 'main'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      run: |
        git clone ${{ github.repository }} .
        git checkout ${{ inputs.ref }}
